title: DENNIS GHARTEY
logo: Dennis.jpg
description: Passionate about making sense of data! Specializing in data visualization, forecasting, and business intelligence.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
